import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ProductCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  stock_quantity: number;
  @ApiProperty()
  status: string;
}

export class Product {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  stock_quantity: number;
  @ApiProperty()
  status: string;
}
