/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('order')
@Index(['order_date'])
@Index(['customer_id'])
@Index(['status'])
export class Order {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'timestamp', nullable: false })
  order_date: Date;

  @Column({ type: 'int' })
  customer_id: number;

  @Column({ type: 'money' })
  total_amount: string;

  @IsOptional({ groups: [UPDATE] })
  @IsNotEmpty({ groups: [CREATE] })
  @Column({ type: 'varchar', length: 255, nullable: false, default: 'pending' })
  status: string;

  // Associations
}
