/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Order } from './Order.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrderService } from './Order.service';
import { OrderController } from './Order.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Order])],
  providers: [OrderService],
  exports: [OrderService],
  controllers: [OrderController],
})
export class OrderModule {}
