/**
 * This file generated by Apso.
 */
import { ProductModule } from './Product/Product.module';
import { OrderModule } from './Order/Order.module';
import { CustomerModule } from './Customer/Customer.module';

export default [ProductModule, OrderModule, CustomerModule];
