/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Product } from './Product.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProductService } from './Product.service';
import { ProductController } from './Product.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Product])],
  providers: [ProductService],
  exports: [ProductService],
  controllers: [ProductController],
})
export class ProductModule {}
