/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Customer } from './Customer.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CustomerService } from './Customer.service';
import { CustomerController } from './Customer.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Customer])],
  providers: [CustomerService],
  exports: [CustomerService],
  controllers: [CustomerController],
})
export class CustomerModule {}
